# Generated by Django 2.0 on 2018-01-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oras', models.CharField(max_length=20)),
                ('tara', models.CharField(max_length=20)),
                ('strada', models.CharField(max_length=40)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Adress')),
            ],
        ),
    ]
