# Generated by Django 2.0 on 2018-01-04 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_account_company_user_account_user_at_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Adress')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
        migrations.AlterField(
            model_name='user_account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.UserProfile'),
        ),
        migrations.AlterField(
            model_name='user_at_company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
