# Generated by Django 2.0 on 2018-01-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180105_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='acont',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_at_company',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user_at_company',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Account'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Company'),
        ),
        migrations.DeleteModel(
            name='user_account',
        ),
        migrations.DeleteModel(
            name='user_at_company',
        ),
    ]
